2023-01-14 00:13:19 | ERROR    | Error on main full history, Cannot save file into a non-existent directory: 'D:\Google Drive Sync\Rzeczy\Projekty_PY\Boty\CyberOasisProjectReborn\history_data\binance_spot\1h' | main | get_full_history.py:206
2023-01-14 00:13:20 | ERROR    | Error on main full history, Cannot save file into a non-existent directory: 'D:\Google Drive Sync\Rzeczy\Projekty_PY\Boty\CyberOasisProjectReborn\history_data\binance_spot\1h' | main | get_full_history.py:206
2023-01-14 00:14:54 | ERROR    | Error on main full history, Cannot save file into a non-existent directory: 'D:\Google Drive Sync\Rzeczy\Projekty_PY\Boty\CyberOasisProjectReborn\history_data\binance_spot\1h' | main | get_full_history.py:206
2023-01-14 00:14:55 | ERROR    | Error on main full history, Cannot save file into a non-existent directory: 'D:\Google Drive Sync\Rzeczy\Projekty_PY\Boty\CyberOasisProjectReborn\history_data\binance_spot\1h' | main | get_full_history.py:206
2023-01-14 00:18:57 | ERROR    | Error on main full history, Cannot save file into a non-existent directory: 'D:\Google Drive Sync\Rzeczy\Projekty_PY\Boty\CyberOasisProjectReborn\history_data\binance_spot\1h' | main | get_full_history.py:206
2023-01-14 00:18:59 | ERROR    | Error on main full history, Cannot save file into a non-existent directory: 'D:\Google Drive Sync\Rzeczy\Projekty_PY\Boty\CyberOasisProjectReborn\history_data\binance_spot\1h' | main | get_full_history.py:206
2023-01-14 00:25:23 | ERROR    | Error on main full history, [WinError 183] Cannot create a file when that file already exists: 'D:\\Google Drive Sync\\Rzeczy\\Projekty_PY\\Boty\\CyberOasisProjectReborn\\history_data\\binance_spot\\1h' | main | get_full_history.py:206
2023-04-03 22:20:15 | ERROR    | Error on main full history, [WinError 183] Cannot create a file when that file already exists: 'D:\\Google Drive Sync\\Rzeczy\\Projekty_PY\\Boty\\history_data\\binance_spot\\1h' | _get_desired_history_for_pair | get_history.py:120
2023-04-03 19:50:09 | ERROR    | Error on main full history, division by zero  | get_full_history | get_history.py:63
2023-04-03 23:15:17 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:63
2023-04-04 08:11:09 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:63
2023-04-04 08:43:54 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:63
2023-04-04 08:47:01 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:63
2023-04-04 08:54:02 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:63
2023-04-04 08:58:09 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:63
2023-04-04 09:17:20 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:63
2023-04-04 22:12:57 | ERROR    | Error on main full history, 'dict' object has no attribute 'to_pickle' | get_full_history | get_history.py:64
2023-04-04 23:56:30 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:64
2023-04-04 23:56:57 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:64
2023-04-04 23:57:15 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 00:02:30 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 00:04:24 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 08:46:05 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 08:50:58 | ERROR    | Error on main full history, list index out of range | get_full_history | get_history.py:64
2023-04-05 08:51:40 | ERROR    | Error on main full history, list index out of range | get_full_history | get_history.py:64
2023-04-05 08:52:11 | ERROR    | Error on main full history, 'NoneType' object has no attribute 'replace' | get_full_history | get_history.py:64
2023-04-05 08:52:34 | ERROR    | Error on main full history, 'NoneType' object has no attribute 'replace' | get_full_history | get_history.py:64
2023-04-05 08:54:50 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 08:56:40 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 08:57:09 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 08:59:31 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 09:00:25 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 09:01:17 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 09:12:04 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:64
2023-04-05 09:13:46 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:64
2023-04-05 09:14:13 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 09:15:57 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 11:44:19 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 11:46:13 | ERROR    | Error on main full history, local variable 'one_pair_df' referenced before assignment | get_full_history | get_history.py:64
2023-04-05 11:46:37 | ERROR    | Error on main full history, local variable 'one_pair_df' referenced before assignment | get_full_history | get_history.py:64
2023-04-05 11:56:34 | ERROR    | Error on main full history, local variable 'one_pair_df' referenced before assignment | get_full_history | get_history.py:64
2023-04-05 11:58:01 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 12:11:44 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 12:15:27 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 12:15:50 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:64
2023-04-05 12:46:43 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:63
2023-04-05 12:46:58 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:63
2023-04-05 12:50:01 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:63
2023-04-05 12:53:05 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:63
2023-04-05 12:53:13 | ERROR    | Error on main full history, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(). | get_full_history | get_history.py:63
2023-04-05 13:03:52 | ERROR    | Error on main full history, [Errno 13] Permission denied: 'D:\\Google Drive Sync\\Rzeczy\\Projekty_PY\\Boty\\CyberOasisProjectReborn\\history_data\\binance_spot\\1h\\BTC-USDT_1h.pickle' | get_full_history | get_history.py:63
2023-04-05 13:06:36 | ERROR    | Error on main full history, [Errno 13] Permission denied: 'D:\\Google Drive Sync\\Rzeczy\\Projekty_PY\\Boty\\CyberOasisProjectReborn\\history_data\\binance_spot\\1h\\BTC-USDT_1h.pickle' | get_full_history | get_history.py:63
2023-04-05 13:12:22 | ERROR    | Error on main full history, [WinError 183] Cannot create a file when that file already exists: 'D:\\Google Drive Sync\\Rzeczy\\Projekty_PY\\Boty\\CyberOasisProjectReborn\\history_data\\binance_spot\\1h' | get_full_history | get_history.py:63
2023-04-05 13:21:33 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:63
2023-04-05 13:22:45 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:63
2023-04-05 13:22:59 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:63
2023-04-05 14:10:43 | ERROR    | Error on main full history, 'NoneType' object has no attribute 'loc' | get_full_history | get_history.py:63
2023-04-05 14:13:35 | ERROR    | Error on main full history, Symbols have mismatching columns | get_full_history | get_history.py:63
2023-04-05 14:22:41 | ERROR    | Error on main full history, No symbols could be fetched | get_full_history | get_history.py:63
2023-04-05 19:48:42 | ERROR    | Error on main full history, 'volume'          | get_full_history | get_history.py:65
2023-04-07 12:59:01 | ERROR    | Error on main full history, [WinError 183] Cannot create a file when that file already exists: 'D:\\Google Drive Sync\\Rzeczy\\Projekty_PY\\Boty\\CyberOasisProjectReborn\\history_data\\binance_spot\\4h' | get_full_history | get_history.py:68
2023-04-07 13:29:55 | ERROR    | Error on main full history, [WinError 183] Cannot create a file when that file already exists: 'D:\\Google Drive Sync\\Rzeczy\\Projekty_PY\\Boty\\CyberOasisProjectReborn\\history_data\\binance_spot\\4h' | get_full_history | get_history.py:68
2023-04-12 13:07:34 | ERROR    | Error on main full history, 'NoneType' object does not support item assignment | get_full_history | get_history.py:68
2023-04-12 13:08:32 | ERROR    | Error on main full history, 'NoneType' object does not support item assignment | get_full_history | get_history.py:68
2023-04-12 13:10:55 | ERROR    | Error on main full history, 'NoneType' object does not support item assignment | get_full_history | get_history.py:68
2023-04-12 14:08:16 | ERROR    | Error on main full history, 'NoneType' object has no attribute 'get' | get_full_history | get_history.py:68
2023-04-18 20:26:26 | ERROR    | Error on main full history, Unsupported timeframe to convert to timedelta | get_full_history | get_history.py:68
2023-04-18 22:09:52 | ERROR    | Error on main full history, Exchange Binance does not support 30MIN timeframe | get_full_history | get_history.py:69
2023-04-18 22:11:38 | ERROR    | Error on main full history, Exchange Binance does not support 30MIN timeframe | get_full_history | get_history.py:69
2023-04-20 23:24:14 | ERROR    | Error on main full history, 'NoneType' object has no attribute 'loc' | get_full_history | get_history.py:72
