2023-01-14 00:13:19 | ERROR    | Error on main full history, Cannot save file into a non-existent directory: 'D:\Google Drive Sync\Rzeczy\Projekty_PY\Boty\CyberOasisProjectReborn\history_data\binance_spot\1h' | main | get_full_history.py:206
2023-01-14 00:13:20 | ERROR    | Error on main full history, Cannot save file into a non-existent directory: 'D:\Google Drive Sync\Rzeczy\Projekty_PY\Boty\CyberOasisProjectReborn\history_data\binance_spot\1h' | main | get_full_history.py:206
2023-01-14 00:14:54 | ERROR    | Error on main full history, Cannot save file into a non-existent directory: 'D:\Google Drive Sync\Rzeczy\Projekty_PY\Boty\CyberOasisProjectReborn\history_data\binance_spot\1h' | main | get_full_history.py:206
2023-01-14 00:14:55 | ERROR    | Error on main full history, Cannot save file into a non-existent directory: 'D:\Google Drive Sync\Rzeczy\Projekty_PY\Boty\CyberOasisProjectReborn\history_data\binance_spot\1h' | main | get_full_history.py:206
2023-01-14 00:18:57 | ERROR    | Error on main full history, Cannot save file into a non-existent directory: 'D:\Google Drive Sync\Rzeczy\Projekty_PY\Boty\CyberOasisProjectReborn\history_data\binance_spot\1h' | main | get_full_history.py:206
2023-01-14 00:18:59 | ERROR    | Error on main full history, Cannot save file into a non-existent directory: 'D:\Google Drive Sync\Rzeczy\Projekty_PY\Boty\CyberOasisProjectReborn\history_data\binance_spot\1h' | main | get_full_history.py:206
2023-01-14 00:25:23 | ERROR    | Error on main full history, [WinError 183] Cannot create a file when that file already exists: 'D:\\Google Drive Sync\\Rzeczy\\Projekty_PY\\Boty\\CyberOasisProjectReborn\\history_data\\binance_spot\\1h' | main | get_full_history.py:206
