2023-01-14 20:52:15 | ERROR    | Error on main market performance, 'str' object has no attribute 'tail' | main | market_performers.py:139
2023-01-23 15:18:32 | ERROR    | Error on main market performance, 'list' object has no attribute 'values' | main | market_performers.py:139
2023-01-23 15:21:16 | ERROR    | Error on main market performance, 'list' object has no attribute 'values' | main | market_performers.py:139
2023-01-23 15:25:25 | ERROR    | Error on main market performance, 'list' object has no attribute 'values' | main | market_performers.py:140
2023-01-23 15:31:53 | ERROR    | Error on main full history, single positional indexer is out-of-bounds | main | get_full_history.py:209
2023-01-23 15:31:53 | ERROR    | Error on main full history, single positional indexer is out-of-bounds | main | get_full_history.py:209
2023-01-23 15:32:04 | ERROR    | Error on main market performance, 'NoneType' object has no attribute 'tail' | main | market_performers.py:141
2023-01-23 15:38:30 | ERROR    | Error on main full history, single positional indexer is out-of-bounds | main | get_full_history.py:209
2023-01-23 15:38:30 | ERROR    | Error on main full history, single positional indexer is out-of-bounds | main | get_full_history.py:209
2023-01-23 15:38:38 | ERROR    | Error on main market performance, 'NoneType' object has no attribute 'tail' | main | market_performers.py:142
2023-01-23 15:47:40 | ERROR    | Error on main full history, 'NoneType' object has no attribute 'loc' | main | get_full_history.py:211
2023-01-23 15:47:41 | ERROR    | Error on main full history, 'NoneType' object has no attribute 'loc' | main | get_full_history.py:211
2023-01-23 15:47:48 | ERROR    | Error on main market performance, 'NoneType' object has no attribute 'tail' | main | market_performers.py:142
2023-01-23 16:03:05 | ERROR    | Error on main full history, 'NoneType' object has no attribute 'loc' | main | get_full_history.py:211
2023-01-23 16:03:05 | ERROR    | Error on main full history, 'NoneType' object has no attribute 'loc' | main | get_full_history.py:211
2023-01-23 16:03:12 | ERROR    | Error on main market performance, 'NoneType' object has no attribute 'tail' | main | market_performers.py:142
2023-01-23 16:19:03 | ERROR    | Error on main market performance, 'NoneType' object has no attribute 'tail' | main | market_performers.py:142
2023-01-23 18:55:23 | ERROR    | Error on main market performance, object of type 'NoneType' has no len() | main | market_performers.py:144
2023-01-23 19:16:21 | ERROR    | Error on main market performance, 'NoneType' object has no attribute 'tail' | main | market_performers.py:144
2023-02-03 12:45:36 | ERROR    | Error on main full history, '_QueryHistory' object has no attribute '_get_history_one_fragment' | main | get_full_history.py:219
2023-02-03 12:49:12 | ERROR    | Error on main full history, '_QueryHistory' object has no attribute '_get_history_one_fragment' | main | get_full_history.py:219
2023-02-03 12:57:17 | ERROR    | Error on main full history, '_QueryHistory' object has no attribute '_get_history_one_fragment' | main | get_full_history.py:219
2023-02-03 18:50:00 | ERROR    | Error on main full history, [WinError 183] Cannot create a file when that file already exists: 'D:\\Google Drive Sync\\Rzeczy\\Projekty_PY\\Boty\\history_data\\binance_spot\\1h' | main | get_full_history.py:87
2023-02-03 18:50:00 | ERROR    | Error on main full history, [WinError 183] Cannot create a file when that file already exists: 'D:\\Google Drive Sync\\Rzeczy\\Projekty_PY\\Boty\\history_data\\binance_spot\\1h' | main | get_full_history.py:87
2023-02-03 18:52:35 | ERROR    | Error on main market performance, single positional indexer is out-of-bounds | main | market_performers.py:139
2023-02-07 13:02:31 | ERROR    | Error on main market performance, 'median momentum' | main | market_performers.py:76
2023-02-07 13:06:11 | ERROR    | Error on main market performance, 'median momentum' | main | market_performers.py:77
2023-02-07 13:07:52 | ERROR    | Error on main market performance, 'median momentum' | main | market_performers.py:77
2023-02-07 13:10:11 | ERROR    | Error on main market performance, 'median momentum' | main | market_performers.py:78
2023-02-07 13:11:40 | ERROR    | Error on main market performance, 'median momentum' | main | market_performers.py:78
2023-02-07 13:14:01 | ERROR    | Error on main market performance, single positional indexer is out-of-bounds | main | market_performers.py:77
2023-02-07 13:55:41 | ERROR    | Error on main market performance, '>' not supported between instances of 'int' and 'NoneType' | main | market_performers.py:78
2023-02-09 14:40:44 | ERROR    | Error on main market performance, 'dict' object attribute 'update' is read-only | main | market_performers.py:118
2023-02-09 14:44:05 | ERROR    | Error on main market performance, [Errno 13] Permission denied: 'performance.xlsx' | main | market_performers.py:118
2023-02-09 14:59:55 | ERROR    | Error on main market performance, 'dict' object attribute 'update' is read-only | main | market_performers.py:117
2023-02-09 15:05:06 | ERROR    | Error on main market performance, int() argument must be a string, a bytes-like object or a real number, not 'NoneType' | main | market_performers.py:117
2023-02-09 15:13:28 | ERROR    | Error on main market performance, 'builtin_function_or_method' object has no attribute '_get_xf_index' | main | market_performers.py:117
2023-02-09 18:17:46 | ERROR    | Error on main market performance, 'builtin_function_or_method' object has no attribute '_get_xf_index' | main | market_performers.py:117
2023-02-09 18:20:36 | ERROR    | Error on main market performance, 'builtin_function_or_method' object has no attribute '_get_xf_index' | main | market_performers.py:117
2023-02-09 18:23:24 | ERROR    | Error on main market performance, 'builtin_function_or_method' object has no attribute '_get_xf_index' | main | market_performers.py:117
2023-02-09 18:33:54 | ERROR    | Error on main market performance, '>' not supported between instances of 'Format' and 'int' | main | market_performers.py:117
2023-02-09 18:50:49 | ERROR    | Error on main market performance, '>' not supported between instances of 'Format' and 'int' | main | market_performers.py:117
2023-02-09 18:53:04 | ERROR    | Error on main market performance, '>' not supported between instances of 'Format' and 'int' | main | market_performers.py:117
2023-02-09 18:56:07 | ERROR    | Error on main market performance, '>' not supported between instances of 'Format' and 'int' | main | market_performers.py:117
2023-02-09 19:01:13 | ERROR    | Error on main market performance, '>' not supported between instances of 'Format' and 'int' | main | market_performers.py:117
2023-02-09 19:04:24 | ERROR    | Error on main market performance, Worksheet.set_column() missing 1 required positional argument: 'last_col' | main | market_performers.py:117
2023-02-09 19:06:29 | ERROR    | Error on main market performance, '<' not supported between instances of 'str' and 'int' | main | market_performers.py:117
2023-02-09 20:29:10 | ERROR    | Error on main market performance, If using all scalar values, you must pass an index | main | market_performers.py:114
2023-02-09 20:31:58 | ERROR    | Error on main market performance, If using all scalar values, you must pass an index | main | market_performers.py:119
2023-02-09 20:39:32 | ERROR    | Error on main market performance, Invalid pair quote currency: BTC/USDT:USDT | main | market_performers.py:119
2023-02-09 20:44:55 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:55 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:55 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:55 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:55 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:55 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:56 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:56 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:56 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:56 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:56 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:56 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:57 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:57 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:57 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:57 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:57 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
2023-02-09 20:44:57 | ERROR    | Error on main full history, binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit of IP(188.47.114.14) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."} | main | get_full_history.py:250
